### ISSUE TITLE
2U Frame

### ISSUE THREAD

**Issue by NickFinbo** [AK51/cubesat#2]
Hi Andy, my team plans to make a 2U CubeSAT. How would this affect the number of frame parts we need to print? Also, if your guide is not at all compatible with 2U, could you point us in the direction of another guide or how we could build it? Thanks.

**Comment by AK51** [comment]
Hi,

For the 2U STL, here is the link
https://www.thingiverse.com/thing:4249498

1 U and 2 U are the same in electronic point of view. There is no compatibility issue. You may need longer wires for putting the electronics.

**Comment by NickFinbo** [comment]
Thanks, but how many of each part will we need?

**Comment by AK51** [comment]
1pcs
Cubesat2U-MCU_AdaptorPlate.stl

2pcs
Cubesat2U-TopBottomPanel.stl

1pcs
Cubesat2U-PlainPanel.stl

1pcs
Cubesat2U-MiddleSection.stl

1pcs
Cubesat2U-RasbiCamPanel.stl

**Comment by NickFinbo** [comment]
Thank you for the help!!
